name: ref_core
description: A simple and lightweight service locator reference library with overrides support for Dart.
version: 1.0.1
repository: https://github.com/Eronildo/simple_ref/tree/master/packages/ref_core
homepage: https://github.com/Eronildo/simple_ref
topics: [service-locator, dependency-injection, reference, ref, testable]

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
